// <auto-generated />
using System;
using DonkeyWork.DeviceManager.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DonkeyWork.DeviceManager.Persistence.Migrations
{
    [DbContext(typeof(DeviceManagerContext))]
    [Migration("20260102232707_AddOSQueryAndAuditTables")]
    partial class AddOSQueryAndAuditTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DeviceManager")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DonkeyWork.DeviceManager.Persistence.Entity.BuildingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Buildings", "DeviceManager");
                });

            modelBuilder.Entity("DonkeyWork.DeviceManager.Persistence.Entity.DeviceAuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("InitiatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Result")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("DeviceId", "Timestamp");

                    b.ToTable("DeviceAuditLogs", "DeviceManager");
                });

            modelBuilder.Entity("DonkeyWork.DeviceManager.Persistence.Entity.DeviceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Architecture")
                        .HasColumnType("text");

                    b.Property<Guid?>("BuildingEntityId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CpuCores")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OSArchitecture")
                        .HasColumnType("text");

                    b.Property<bool>("Online")
                        .HasColumnType("boolean");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("text");

                    b.Property<string>("OperatingSystemVersion")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long?>("TotalMemoryBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BuildingEntityId");

                    b.HasIndex("RoomId");

                    b.ToTable("Devices", "DeviceManager");
                });

            modelBuilder.Entity("DonkeyWork.DeviceManager.Persistence.Entity.DeviceRegistrationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ThreeWordRegistration")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("DeviceRegistrations", "DeviceManager");
                });

            modelBuilder.Entity("DonkeyWork.DeviceManager.Persistence.Entity.OSQueryExecutionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeviceCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid?>("QueryHistoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedAt");

                    b.HasIndex("QueryHistoryId");

                    b.ToTable("OSQueryExecutions", "DeviceManager");
                });

            modelBuilder.Entity("DonkeyWork.DeviceManager.Persistence.Entity.OSQueryExecutionResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ExecutionTimeMs")
                        .HasColumnType("integer");

                    b.Property<string>("RawJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ExecutionId");

                    b.ToTable("OSQueryExecutionResults", "DeviceManager");
                });

            modelBuilder.Entity("DonkeyWork.DeviceManager.Persistence.Entity.OSQueryHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExecutionCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OSQueryHistory", "DeviceManager");
                });

            modelBuilder.Entity("DonkeyWork.DeviceManager.Persistence.Entity.RoomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Rooms", "DeviceManager");
                });

            modelBuilder.Entity("DonkeyWork.DeviceManager.Persistence.Entity.TenantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InitialUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants", "DeviceManager");
                });

            modelBuilder.Entity("DonkeyWork.DeviceManager.Persistence.Entity.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Users", "DeviceManager");
                });

            modelBuilder.Entity("DonkeyWork.DeviceManager.Persistence.Entity.DeviceAuditLogEntity", b =>
                {
                    b.HasOne("DonkeyWork.DeviceManager.Persistence.Entity.DeviceEntity", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("DonkeyWork.DeviceManager.Persistence.Entity.DeviceEntity", b =>
                {
                    b.HasOne("DonkeyWork.DeviceManager.Persistence.Entity.BuildingEntity", null)
                        .WithMany("Devices")
                        .HasForeignKey("BuildingEntityId");

                    b.HasOne("DonkeyWork.DeviceManager.Persistence.Entity.RoomEntity", "Room")
                        .WithMany("Devices")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DonkeyWork.DeviceManager.Persistence.Entity.OSQueryExecutionEntity", b =>
                {
                    b.HasOne("DonkeyWork.DeviceManager.Persistence.Entity.OSQueryHistoryEntity", "QueryHistory")
                        .WithMany("Executions")
                        .HasForeignKey("QueryHistoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("QueryHistory");
                });

            modelBuilder.Entity("DonkeyWork.DeviceManager.Persistence.Entity.OSQueryExecutionResultEntity", b =>
                {
                    b.HasOne("DonkeyWork.DeviceManager.Persistence.Entity.DeviceEntity", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DonkeyWork.DeviceManager.Persistence.Entity.OSQueryExecutionEntity", "Execution")
                        .WithMany("Results")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Execution");
                });

            modelBuilder.Entity("DonkeyWork.DeviceManager.Persistence.Entity.RoomEntity", b =>
                {
                    b.HasOne("DonkeyWork.DeviceManager.Persistence.Entity.BuildingEntity", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("DonkeyWork.DeviceManager.Persistence.Entity.BuildingEntity", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DonkeyWork.DeviceManager.Persistence.Entity.OSQueryExecutionEntity", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("DonkeyWork.DeviceManager.Persistence.Entity.OSQueryHistoryEntity", b =>
                {
                    b.Navigation("Executions");
                });

            modelBuilder.Entity("DonkeyWork.DeviceManager.Persistence.Entity.RoomEntity", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
